version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cargo_link_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cargo_link
      POSTGRES_USER: cargo_link
      POSTGRES_PASSWORD: cargo_link
    ports:
      - "5432:5432"
    volumes:
      - cargo_link_pgdata:/var/lib/postgresql/data

volumes:
  cargo_link_pgdata: